# Alex Lombry brew's file
brew tap homebrew/php

brew install ack
brew install tree
brew install wget
brew install youtube-dl
brew install ngrep
brew install htop

# development tools
brew install tmux
brew install ccat
brew install Cmake
brew install nvm

# Install Powerline for vim
# Powerline already configured on my .vimrc file
brew install python
brew install coreutils
brew install macvim --override-system-vim --with-cscope --with-lua --HEAD
brew install vim --env-std --override-system-vim --with-lua
brew install reattach-to-user-namespace

# Install Cask
brew install caskroom/cask/brew-cask