# https://taskfile.dev
version: '2'

vars:
  GREETING: Hello, World!

tasks:
  # Default
  default:
    cmds:
      - task --list

  # Setup OS
  os:
    silent: true
    desc: "Setup OS"
    cmds:
      - echo "Setup OS starting..."
      - bash scripts/macos/macos.sh
      - echo "Setup OS done!"

  # Setup Zsh
  zsh:
    silent: true
    desc: "Setup Oh My Zsh"
    cmds:
      - echo "Setup OMZ - Core"
      - if [ ! -d "oh-my-zsh" ]; then curl -L http://install.ohmyz.sh | sh; fi
      - chsh -s $(which zsh);
      - echo 'source ~/.zsh_ext' >> ~/.zshrc
      - echo "Setup ZSH done!"

  # Setup Vim
  vim:
    silent: true
    desc: "Setup Vim"
    cmds:
      - echo "Setup Vim"
      - bash scripts/vim/vim.sh
      - echo "Setup Vim done!"

  # Setup Links
  links:
    silent: true
    desc: "Setup Symlinks of configuration files"
    cmds:
      - echo "Setup Vim"
      - bash scripts/macos/links.sh
      - echo "Setup Links done!"
