# https://taskfile.dev
version: '2'

tasks:
  default:
    cmds:
      - task --list

  os:
    silent: true
    desc: "Configure macOS default system"
    cmds:
      - bash scripts/macos/macos.sh
      - echo "Setup OS done!"

  zsh:
    silent: true
    desc: "Install oh my zsh and source zsh extension file"
    cmds:
      - if [ ! -d "oh-my-zsh" ]; then curl -L http://install.ohmyz.sh | sh; fi
      - chsh -s $(which zsh);
      - echo 'source ~/.zsh_ext' >> ~/.zshrc
      - echo "Setup ZSH done!"

  vim:
    silent: true
    desc: "Install Vim packages with Vundle and plugins"
    cmds:
      - bash scripts/vim/vim.sh
      - echo "Setup Vim done!"

  links:
    silent: true
    desc: "Create all dotfiles symlinks"
    cmds:
      - bash scripts/macos/links.sh
      - echo "Setup Links done!"

  sublime:
    silent: true
    desc: "Setup Sublime Text 3 Dropbox preferences"
    cmds:
      - echo "Setup Sublime Text 3"
      - rm -rf cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
      - ln -s /Users/alex/Dropbox/Sublime/User /Users/alex/Library/Application\ Support/Sublime\ Text\ 3/Packages/User

  php:
    silent: true
    desc: "Forcing reinstallation of PHP"
    cmds:
      - echo "Setup PHP "
      - bash scripts/macos/php.sh
      - echo "Setup PHP done!"
