# https://taskfile.dev

version: '2'

vars:
  GREETING: Hello, World!

tasks:
  # Default
  default:
    cmds:
      - task --list

  # Global setup
  setup:
    silent: true
    desc: "Setup installation"
    cmds:
      - task: "setup:os"
      - task: "setup:zsh"

  # Setup OS
  "setup:os":
    silent: true
    desc: "Setup OS"
    cmds:
      - echo "Setup OS starting..."
      - bash macos/macos.sh
      - echo "Setup OS done!"

  # Setup Zsh
  "setup:zsh":
    silent: true
    desc: "Setup OS"
    cmds:
      - echo "Setup OMZ - Core"
      - if [ ! -d "oh-my-zsh" ]; then curl -L http://install.ohmyz.sh | sh; fi
      - curl -L http://install.ohmyz.sh | sh
      - chsh -s $(which zsh);
      - echo "Setup ZSH done!"

  # Setup Zsh
  "setup:vim":
    silent: true
    desc: "Setup Vim"
    cmds:
      - echo "Setup Vim"
      - bash vim/vim.sh
      - echo "Setup Vim done!"
