# https://taskfile.dev
version: '2'

tasks:
  default:
    cmds:
      - task --list

  os:
    silent: true
    desc: "Configure macOS default system"
    cmds:
      - bash scripts/macos/macos.sh
      - echo "Setup OS done!"

  zsh:
    silent: true
    desc: "Install oh my zsh and source zsh extension file"
    cmds:
      - if [ ! -d "oh-my-zsh" ]; then curl -L http://install.ohmyz.sh | sh; fi
      - chsh -s $(which zsh);
      - echo 'source ~/.zsh_ext' >> ~/.zshrc
      - echo "Setup ZSH done!"

  vim:
    silent: true
    desc: "Install Vim packages with Vundle and plugins"
    cmds:
      - bash scripts/vim/vim.sh
      - echo "Setup Vim done!"

  links:
    silent: true
    desc: "Create all dotfiles symlinks"
    cmds:
      - bash scripts/macos/links.sh
      - echo "Setup Links done!"

  sublime:
    silent: true
    desc: "Setup Sublime Text 3 Dropbox preferences"
    cmds:
      - echo "Setup Sublime Text 3"
      - rm -rf cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
      - ln -s /Users/alex/Dropbox/Sublime/User /Users/alex/Library/Application\ Support/Sublime\ Text\ 3/Packages/User

  php:
    silent: true
    desc: "Forcing reinstallation of PHP"
    cmds:
      - echo "Setup PHP "
      - bash scripts/macos/php.sh
      - echo "Setup PHP done!"

  dev-start:
    silent: true
    desc: "Launch Docker with Redis, MySQL and Minio"
    cmds:
      - docker-compose -f ./scripts/macos/docker-compose.yml up -d
      - docker-compose -f ./scripts/macos/docker-compose.yml start createbuckets

  dev-stop:
    silent: true
    desc: "Launch Docker with Redis, MySQL and Minio"
    cmds:
      - docker-compose -f ./scripts/macos/docker-compose.yml down

  yabai-install:
    silent: true
    desc: "Installing Yabai for Window Management"
    cmds:
      - brew install koekeishiya/formulae/yabai
      - sudo yabai --install-sa
      - brew services start yabai
      - killall Dock
      - brew install koekeishiya/formulae/skhd
      - brew services start skhd
      - chmod +x ~/.yabairc
      - chmod +x ~/.skhdrc

  yabai-remove:
    silent: true
    desc: "Uninstalling Yabai for Window Management"
    cmds:
      - brew services stop yabai skhd
      - sudo yabai --uninstall-sa
      - brew uninstall yabai skhd
      - rm -rf /usr/local/var/log/yabai
      - rm ~/.yabairc
      - rm ~/.skhdrc
      - rm /tmp/yabai_$USER.lock
      - rm /tmp/yabai_$USER.socket
      - rm /tmp/yabai-sa_$USER.socket
      - killall Dock

  yabai-update:
    silent: true
    desc: "Update Yabai for Window Management"
    cmds:
      - brew services stop yabai
      - brew upgrade yabai
      - brew services start yabai
      - sudo yabai --uninstall-sa
      - sudo yabai --install-sa
      - killall Dock
