# Alex Lombry brew's file
ack
tree
wget
youtube-dl
ngrep
htop

# development tools
tmux
ccat
Cmake
nvm

# Install Powerline for vim
# Powerline already configured on my .vimrc file
python
coreutils
macvim --override-system-vim --with-cscope --with-lua --HEAD
vim --env-std --override-system-vim --with-lua
reattach-to-user-namespace

# Install Cask
caskroom/cask/brew-cask