export ZSH="$HOME/.oh-my-zsh"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
#ZSH_THEME="dracula"
#ZSH_THEME="awesomepanda"
ZSH_THEME="smt"

plugins=(git zsh-completions extract ssh-agent gpg-agent docker docker-compose fancy-ctrl-z)

autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

export PATH="/usr/local/opt/mysql-client/bin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"

export CODEFOLDER="$HOME/code"
autoload -U promptinit; promptinit

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

source ~/.zsh_ext
source ~/.mano.zsh
