# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export DOTFILES=$HOME/dotfiles

export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export DISPLAY=":0.0"
export EDITOR='vim'

# zsh builtin to re-run last line. dangerous. do not want. use `!!`.
disable r

# define the code directory
if [[ -d ~/Code ]]; then
    export CODE_DIR=~/Code
fi

# load all zsh config files
#for config ($DOTFILES/zsh/*.zsh) source $config

# Antigen configuration
source $DOTFILES/zsh/antigen.zsh
antigen use oh-my-zsh
antigen bundle git
antigen bundle osx
antigen bundle kubectl
antigen bundle jsontools
antigen bundle zsh-users/zsh-syntax-highlighting
antigen apply

# Theme
ZSH_THEME="agnoster"

plugins=(zsh-autosuggestions git brew command-not-found jsontools osx)

# Zsh sourcecustom
source $ZSH/oh-my-zsh.sh
for script in $DOTFILES/zsh/*.zsh; do source $script; done
source ~/.pandacraft.zsh

# User configuration
export TERM="xterm-256color"
export GEM_HOME=$HOME/.gem
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export GO111MODULE=on
export GOPATH="$HOME/Code/"
export HOMEBREW_NO_AUTO_UPDATE=1
export SSH_KEY_PATH="~/.ssh/id_rsa"

export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
PATH+=:/usr/local/opt/coreutils/libexec/gnubin
PATH+=:$HOME/.composer/vendor/bin
PATH+=:/usr/local/opt/coreutils/libexec/gnubin
PATH+=:/usr/local/opt/python/libexec/bin
PATH+=:/usr/local/opt/php@7.1/bin
PATH+=:/usr/local/opt/php@7.1/sbin
PATH+=:$GOROOT/bin
PATH+=$GEM_HOME/bin:$PATH
PATH+=/usr/local/opt/nss/bin


export XDEBUG_CONFIG="idekey=VSCODE"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

export APP_ENV="local"
export APPLICATION_FOLDER=/Users/alex/Code
export HOMEBREW_FORCE_BREWED_CURL=1

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

cdpath=(~/Code/)

# Keypad
# 0 . Enter
bindkey -s "^[Op" "0"
bindkey -s "^[Ol" "."
bindkey -s "^[OM" "^M"
# 1 2 3
bindkey -s "^[Oq" "1"
bindkey -s "^[Or" "2"
bindkey -s "^[Os" "3"
# 4 5 6
bindkey -s "^[Ot" "4"
bindkey -s "^[Ou" "5"
bindkey -s "^[Ov" "6"
# 7 8 9
bindkey -s "^[Ow" "7"
bindkey -s "^[Ox" "8"
bindkey -s "^[Oy" "9"
# + -  * /
bindkey -s "^[Ok" "+"
bindkey -s "^[Om" "-"
bindkey -s "^[Oj" "*"
bindkey -s "^[Oo" "/"

# History file
export HISTFILE=~/.zsh_history

# Don't show duplicate history entires
setopt hist_find_no_dups

# Remove unnecessary blanks from history
setopt hist_reduce_blanks

# Share history between instances
setopt share_history

# fix delete key on macOS
[ $MACOS ] && bindkey "\e[3~" delete-char


#source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
#source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"

## PERL PATH VAR
#PATH="/Users/alex/perl5/bin${PATH:+:${PATH}}"; export PATH;
#PERL5LIB="/Users/alex/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
#PERL_LOCAL_LIB_ROOT="/Users/alex/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
#PERL_MB_OPT="--install_base \"/Users/alex/perl5\""; export PERL_MB_OPT;
#PERL_MM_OPT="INSTALL_BASE=/Users/alex/perl5"; export PERL_MM_OPT;

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
#export SDKMAN_DIR="/Users/alex/.sdkman"
#[[ -s "/Users/alex/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/alex/.sdkman/bin/sdkman-init.sh"
POWERLEVEL9K_MODE='nerdfont-complete'