# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export DOTFILES=$HOME/dotfiles

# autoload -U promptinit; promptinit
# prompt pure

# define the code directory
if [[ -d ~/Code ]]; then
    export CODE_DIR=~/Code
fi

# load all zsh config files
for config ($DOTFILES/zsh/*.zsh) source $config

# Theme
# ZSH_THEME="robbyrussell"
# ZSH_THEME="smt"
ZSH_THEME="gnzh"

#plugins=(git brew vagrant composer command-not-found github)

source $ZSH/oh-my-zsh.sh

export EDITOR='vim'

# User configuration

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH="$(brew --prefix homebrew/php/php71)/bin:$PATH"
export PATH="$HOME/.composer/vendor/bin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

# Visual Studio Code Xdebug configuration for PHP Debug Plugin
export XDEBUG_CONFIG="idekey=VSCODE"

# Java home for Android development
export JAVA_HOME=/Applications/Android\ Studio.app/Contents/jre/jdk/Contents/Home

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# ssh
# export SSH_KEY_PATH="~/.ssh/id_rsa"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
export TERM="xterm-256color"
export PATH="/usr/local/sbin:$PATH"

export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH

export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export APP_ENV="mac"

# function powerline_precmd() {
#     # PS1="$(powerline-shell --shell zsh $?)"
# }
# 
# function install_powerline_precmd() {
#   for s in "${precmd_functions[@]}"; do
#     if [ "$s" = "powerline_precmd" ]; then
#       return
#     fi
#   done
#   # precmd_functions+=(powerline_precmd)
# }
# 
# if [ "$TERM" != "linux" ]; then
#     # install_powerline_precmd
# fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

cdpath=(~/Zenchef ~/Code/)
