# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export DOTFILES=$HOME/dotfiles

# define the code directory
if [[ -d ~/Code ]]; then
    export CODE_DIR=~/Code
fi

# load all zsh config files
for config ($DOTFILES/zsh/*.zsh) source $config

# Theme
# ZSH_THEME="agnoster"
ZSH_THEME="taybalt"

# plugins=(zsh-autosuggestions git brew command-not-found github kubectl)
plugins=(git brew github kubectl)

source $ZSH/oh-my-zsh.sh
source ~/.owp.zsh

# User configuration
export EDITOR='vim'

export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH="$HOME/.composer/vendor/bin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
export PATH=$PATH:$(go env GOPATH)/bin

# Visual Studio Code Xdebug configuration for PHP Debug Plugin
export XDEBUG_CONFIG="idekey=VSCODE"

# Java home for Android development
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

#Spark variable
export SPARK_HOME=/usr/local/Cellar/apache-spark/2.3.2/libexec
export PATH=$SPARK_HOME/bin:$PATH
export PYSPARK_PYTHON=/usr/local/Cellar/python/3.7.0/libexec/bin/python
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

# ssh
export SSH_KEY_PATH="~/.ssh/id_rsa"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
export TERM="xterm-256color"

export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH

export HOMEBREW_CASK_OPTS="--appdir=/Applications"

function powerline_precmd() {
    PS1="$(powerline-shell --shell zsh $?)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ]; then
    install_powerline_precmd
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

cdpath=(~/OWP ~/Code/)

# Keypad
# 0 . Enter
bindkey -s "^[Op" "0"
bindkey -s "^[Ol" "."
bindkey -s "^[OM" "^M"
# 1 2 3
bindkey -s "^[Oq" "1"
bindkey -s "^[Or" "2"
bindkey -s "^[Os" "3"
# 4 5 6
bindkey -s "^[Ot" "4"
bindkey -s "^[Ou" "5"
bindkey -s "^[Ov" "6"
# 7 8 9
bindkey -s "^[Ow" "7"
bindkey -s "^[Ox" "8"
bindkey -s "^[Oy" "9"
# + -  * /
bindkey -s "^[Ok" "+"
bindkey -s "^[Om" "-"
bindkey -s "^[Oj" "*"
bindkey -s "^[Oo" "/"

# History file
export HISTFILE=~/.zsh_history

# Don't show duplicate history entires
setopt hist_find_no_dups

# Remove unnecessary blanks from history
setopt hist_reduce_blanks

# Share history between instances
setopt share_history

# fix delete key on macOS
[ $MACOS ] && bindkey "\e[3~" delete-char
export APP_ENV="mac"
export APPLICATION_FOLDER=/Users/alex/Code

source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"

export HOMEBREW_FORCE_BREWED_CURL=1
export DEV=true

eval $(thefuck --alias)
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/alex/.sdkman"
[[ -s "/Users/alex/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/alex/.sdkman/bin/sdkman-init.sh"
