# Laravel and Composer
alias pa="php artisan"
alias pacc="php artisan cache:clear"
alias par="php artisan routes"
alias pam="php artisan migrate"
alias pam:r="php artisan migrate:refresh"
alias pase="php artisan serve"
alias pam:roll="php artisan migrate:rollback"
alias pam:rs="php artisan migrate:refresh --seed"
alias pda="php artisan dumpautoload"
alias cu="composer update -vvv"
alias ci="composer install"
alias cda="composer dump-autoload -o"
alias csu="composer self-update"